// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSzQhD4hv3TypyIYy5QVr9iRL_w1z-tOk',
    appId: '1:347211940631:web:e5eb80b3f6093a512aed52',
    messagingSenderId: '347211940631',
    projectId: 'break-down-6788d',
    authDomain: 'break-down-6788d.firebaseapp.com',
    storageBucket: 'break-down-6788d.appspot.com',
    measurementId: 'G-Q1ZG4GB30T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVXka7f5_8-so0Ju7O6-h11lTcqITYC94',
    appId: '1:347211940631:android:2d1e93fa9e9887362aed52',
    messagingSenderId: '347211940631',
    projectId: 'break-down-6788d',
    storageBucket: 'break-down-6788d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDInjjbOHfvYIItUbQvbMvLZExDolAkMAA',
    appId: '1:347211940631:ios:9d6372e28d56483e2aed52',
    messagingSenderId: '347211940631',
    projectId: 'break-down-6788d',
    storageBucket: 'break-down-6788d.appspot.com',
    iosBundleId: 'com.example.breakDownAssistance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDInjjbOHfvYIItUbQvbMvLZExDolAkMAA',
    appId: '1:347211940631:ios:9922eaeb02234bec2aed52',
    messagingSenderId: '347211940631',
    projectId: 'break-down-6788d',
    storageBucket: 'break-down-6788d.appspot.com',
    iosBundleId: 'com.example.breakDownAssistance.RunnerTests',
  );
}
